use crate::constants::*;
use crate::list_ent::*;
use crate::diff_doub::*;

use std::collections::LinkedList;

#[derive(Clone)]
pub struct Node {
    pub label : usize,
    pub fluid : bool,
    pub on_surf : bool,
    pub num_dof : usize,
    pub dof_index : [usize; 6],
    pub sorted_rank : usize,
    pub coord : [f64; 3],
    pub coord_dfd0 : [DiffDoub0; 3],
    pub coord_dfd1 : [DiffDoub1; 3],
    pub displacement : [f64; 6],
    pub velocity : [f64; 6],
    pub fl_vel : [f64; 3],
    pub fl_vel_dot : [f64; 3],
    pub acceleration : [f64; 6],
    pub temperature : f64,
    pub temp_change_rate : f64,
    pub fl_den : f64,
    pub fl_den_dot : f64,
    pub turb_e : f64,
    pub turb_edot : f64,
    pub prev_disp : [f64; 6],
    pub prev_vel : [f64; 6],
    pub prev_fl_vel : [f64; 3],
    pub p_fl_vel_lf : [f64; 3],
    pub prev_fl_vel_dot : [f64; 3],
    pub prev_acc : [f64; 6],
    pub prev_temp : f64,
    pub p_temp_lf : f64,
    pub prev_tdot : f64,
    pub prev_fl_den : f64,
    pub p_fl_den_lf : f64,
    pub prev_fl_den_dot : f64,
    pub prev_turb_e : f64,
    pub prev_turb_edot : f64,
    pub p_turb_elf : f64,
    pub initial_disp : [f64; 6],
    pub initial_vel : [f64; 6],
    pub initial_fl_vel : [f64; 3],
    pub initial_fl_vel_dot : [f64; 3],
    pub initial_acc : [f64; 6],
    pub initial_temp : f64,
    pub initial_tdot : f64,
    pub initial_fl_den : f64,
    pub initial_fl_den_dot : f64,
    pub initial_turb_e : f64,
    pub initial_turb_edot : f64,
    pub max_fl_den : f64,
    pub d_var_lst : LinkedList<IDCapsule>,
    pub el_lst : LinkedList<DualInt>,
    pub conn_nds : LinkedList<usize>,
}

impl Node {
    pub fn new() -> Node {
        Node {
            label : MAX_INT,
            fluid : false,
            on_surf : false,
            num_dof : 3usize,
            dof_index : [MAX_INT; 6],
            sorted_rank : MAX_INT,
            coord : [0f64; 3],
            coord_dfd0 : [DiffDoub0::new(); 3],
            coord_dfd1 : [DiffDoub1::new(); 3],
            displacement : [0f64; 6],
            velocity : [0f64; 6],
            fl_vel : [0f64; 3],
            fl_vel_dot : [0f64; 3],
            acceleration : [0f64; 6],
            temperature : 0f64,
            temp_change_rate : 0f64,
            fl_den : 0f64,
            fl_den_dot : 0f64,
            turb_e : 0f64,
            turb_edot : 0f64,
            prev_disp : [0f64; 6],
            prev_vel : [0f64; 6],
            prev_fl_vel : [0f64; 3],
            p_fl_vel_lf : [0f64; 3],
            prev_fl_vel_dot : [0f64; 3],
            prev_acc : [0f64; 6],
            prev_temp : 0f64,
            p_temp_lf : 0f64,
            prev_tdot : 0f64,
            prev_fl_den : 0f64,
            p_fl_den_lf : 0f64,
            prev_fl_den_dot : 0f64,
            prev_turb_e : 0f64,
            prev_turb_edot : 0f64,
            p_turb_elf : 0f64,
            initial_disp : [0f64; 6],
            initial_vel : [0f64; 6],
            initial_fl_vel : [0f64; 3],
            initial_fl_vel_dot : [0f64; 3],
            initial_acc : [0f64; 6],
            initial_temp : 0f64,
            initial_tdot : 0f64,
            initial_fl_den : 0f64,
            initial_fl_den_dot : 0f64,
            initial_turb_e : 0f64,
            initial_turb_edot : 0f64,
            max_fl_den : 1f64,
            d_var_lst : LinkedList::new(),
            el_lst : LinkedList::new(),
            conn_nds : LinkedList::new(),
        }
    }
}
